# Import Keras and Packages

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input
from keras.utils import to_categorical

##### when working with with convolutional neural networks in particular we will need additional packages

In [2]:
from keras.layers import Conv2D #it is for adding conv layer
from keras.layers import MaxPooling2D
from keras.layers import Flatten

### Convolutional Neural Network with One Set of Convolutional and Pooling Layers

In [12]:
#import data from mnist lib
from keras.datasets import mnist

#Load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [13]:
print(X_train.shape)

(60000, 28, 28)


In [14]:
print(X_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

In [15]:
# reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')

In [16]:
print(X_train[0].shape)

(28, 28, 1)


In [11]:
print(X_test[0])

[[[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]]

 [[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]]

 [[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]]

 [[  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [  0.]
  [ 

In [17]:
print(X_train.shape)

(60000, 28, 28, 1)


##### Let's normalize the pixel values to be between 0 and 1

In [18]:
X_train = X_train / 255 # normalize training data
X_test = X_test / 255 # normalize test data

##### Next, let's convert the target variable into binary categories

In [19]:
print("Before to categorical",y_train[0])
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
num_classes = y_test.shape[1] # number of categories

Before to categorical 5


In [20]:
print(y_train[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [22]:
#Lets define a function that creates our model.
def convolutional_model():
    #create model
    model = Sequential()
    model.add(Input(shape=(28,28,1)))
    model.add(Conv2D(16,(5,5),strides=(1,1),activation='relu'))
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
    ######
    model.add(Flatten())
    model.add(Dense(100,activation='relu'))
    model.add(Dense(num_classes,activation='softmax'))

    #######compile model
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    return model


##### Finally, let's call the function to create the model, and then let's train it and evaluate it.

In [23]:
#Call the fun and build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

#evaluate the model
scores=model.evaluate(X_test,y_test,verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Epoch 1/10
300/300 - 21s - loss: 0.2867 - accuracy: 0.9215 - val_loss: 0.0967 - val_accuracy: 0.9721 - 21s/epoch - 71ms/step
Epoch 2/10
300/300 - 2s - loss: 0.0853 - accuracy: 0.9753 - val_loss: 0.0663 - val_accuracy: 0.9789 - 2s/epoch - 6ms/step
Epoch 3/10
300/300 - 2s - loss: 0.0604 - accuracy: 0.9823 - val_loss: 0.0556 - val_accuracy: 0.9811 - 2s/epoch - 5ms/step
Epoch 4/10
300/300 - 1s - loss: 0.0462 - accuracy: 0.9864 - val_loss: 0.0467 - val_accuracy: 0.9848 - 1s/epoch - 4ms/step
Epoch 5/10
300/300 - 8s - loss: 0.0374 - accuracy: 0.9887 - val_loss: 0.0499 - val_accuracy: 0.9835 - 8s/epoch - 25ms/step
Epoch 6/10
300/300 - 9s - loss: 0.0321 - accuracy: 0.9904 - val_loss: 0.0426 - val_accuracy: 0.9852 - 9s/epoch - 29ms/step
Epoch 7/10
300/300 - 3s - loss: 0.0264 - accuracy: 0.9916 - val_loss: 0.0353 - val_accuracy: 0.9877 - 3s/epoch - 11ms/step
Epoch 8/10
300/300 - 3s - loss: 0.0219 - accuracy: 0.9931 - val_loss: 0.0376 - val_accuracy: 0.9882 - 3s/epoch - 11ms/step
Epoch 9/10
300/30

## Convolutional Neural Network with Two Sets of Convolutional and Pooling Layers

In [25]:
#  redefine our convolutional model so that it has two convolutional and pooling layers

def convolutional_model():
    model = Sequential()
    model.add(Input(shape=(28,28,1)))
    model.add(Conv2D(16,(5,5),strides=(1,1),activation='relu'))
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))

    ################2nd layer of pooling and conv
    model.add(Conv2D(16,(5,5),strides=(1,1),activation='relu'))
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
    ##################output layer
    model.add(Flatten())
    model.add(Dense(100,activation='relu'))
    model.add(Dense(num_classes,activation='softmax'))
    ######compile model
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    return model

In [26]:
# build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

# evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Epoch 1/10
300/300 - 2s - loss: 0.3778 - accuracy: 0.8914 - val_loss: 0.1133 - val_accuracy: 0.9652 - 2s/epoch - 8ms/step
Epoch 2/10
300/300 - 2s - loss: 0.0942 - accuracy: 0.9715 - val_loss: 0.0654 - val_accuracy: 0.9794 - 2s/epoch - 5ms/step
Epoch 3/10
300/300 - 2s - loss: 0.0667 - accuracy: 0.9795 - val_loss: 0.0445 - val_accuracy: 0.9862 - 2s/epoch - 5ms/step
Epoch 4/10
300/300 - 2s - loss: 0.0527 - accuracy: 0.9836 - val_loss: 0.0448 - val_accuracy: 0.9866 - 2s/epoch - 5ms/step
Epoch 5/10
300/300 - 2s - loss: 0.0426 - accuracy: 0.9868 - val_loss: 0.0363 - val_accuracy: 0.9885 - 2s/epoch - 5ms/step
Epoch 6/10
300/300 - 2s - loss: 0.0369 - accuracy: 0.9888 - val_loss: 0.0372 - val_accuracy: 0.9879 - 2s/epoch - 5ms/step
Epoch 7/10
300/300 - 2s - loss: 0.0323 - accuracy: 0.9898 - val_loss: 0.0373 - val_accuracy: 0.9884 - 2s/epoch - 5ms/step
Epoch 8/10
300/300 - 2s - loss: 0.0287 - accuracy: 0.9905 - val_loss: 0.0317 - val_accuracy: 0.9898 - 2s/epoch - 5ms/step
Epoch 9/10
300/300 - 1s 

In [27]:
# build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=1024, verbose=2)

# evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Epoch 1/10
59/59 - 2s - loss: 0.9139 - accuracy: 0.7660 - val_loss: 0.2749 - val_accuracy: 0.9220 - 2s/epoch - 33ms/step
Epoch 2/10
59/59 - 1s - loss: 0.2304 - accuracy: 0.9322 - val_loss: 0.1689 - val_accuracy: 0.9515 - 858ms/epoch - 15ms/step
Epoch 3/10
59/59 - 1s - loss: 0.1555 - accuracy: 0.9549 - val_loss: 0.1155 - val_accuracy: 0.9651 - 794ms/epoch - 13ms/step
Epoch 4/10
59/59 - 1s - loss: 0.1194 - accuracy: 0.9654 - val_loss: 0.0927 - val_accuracy: 0.9728 - 783ms/epoch - 13ms/step
Epoch 5/10
59/59 - 1s - loss: 0.0997 - accuracy: 0.9703 - val_loss: 0.0786 - val_accuracy: 0.9761 - 785ms/epoch - 13ms/step
Epoch 6/10
59/59 - 1s - loss: 0.0866 - accuracy: 0.9745 - val_loss: 0.0686 - val_accuracy: 0.9788 - 794ms/epoch - 13ms/step
Epoch 7/10
59/59 - 1s - loss: 0.0774 - accuracy: 0.9769 - val_loss: 0.0604 - val_accuracy: 0.9815 - 791ms/epoch - 13ms/step
Epoch 8/10
59/59 - 1s - loss: 0.0695 - accuracy: 0.9793 - val_loss: 0.0578 - val_accuracy: 0.9819 - 780ms/epoch - 13ms/step
Epoch 9/10
