## Creating Our Own neural network layers

In [5]:
#To create a custom layers we need to inherit the Layer class from layers
from tensorflow.keras.layers import Layer
import tensorflow as tf

from Project_Classification_and_Captioning_Aircraft import summary


class MycustomLayer(Layer):
    #we need to implement three methods
    def __init__(self,units=32,**kwargs):
        super(MycustomLayer,self).__init__(**kwargs)
        self.units = units
    def build(self,input_shape):
        self.w = self.add_weight(shape=(input_shape[-1],self.units),initializer='random_normal',trainable=True)
        self.b = self.add_weight(shape=(self.units,),initializer='zeros',trainable=True)
    def call(self,inputs):
        return tf.matmul(inputs,self.w)+self.b

## Creating a custom layer with activation function in farward pass

In [ ]:
class MyCustomLayer_act(Layers)

In [17]:
model= MycustomLayer(name='custom')

NameError: name 'summary' is not defined

In [10]:
print(model.units)

32


In [15]:
input=tf.constant([[1,2,3,2,1,12,1,1,2,1,121]],dtype=tf.float32)
model(input)

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[-5.00576  , -1.6831801, -1.5680854,  5.5010943, -9.488812 ,
         5.967861 ,  0.8839537,  2.3869379, -0.5575425,  1.1536813,
        -2.6363063, -0.6560843,  0.6081433,  2.2747295, -6.297249 ,
         0.6362763,  5.2213607,  1.8836602, -3.445265 ,  7.1244297,
        -0.5848143, -7.621829 ,  8.483746 , -3.3955622,  1.4317915,
        -4.2568746, -3.6493943,  7.101535 ,  5.6131845, -6.140281 ,
        -5.5187216, -8.097674 ]], dtype=float32)>

In [18]:
print(model.w)

<Variable path=custom/variable, shape=(11, 32), dtype=float32, value=[[-0.08912103  0.0382664   0.02825385 -0.03906588  0.00193473 -0.00664705
  -0.08088135  0.08813971  0.00586507 -0.02260446  0.01418705 -0.00976022
   0.01281479 -0.0418446  -0.06458714 -0.06377434  0.04788006  0.03671731
   0.05620714  0.0125232   0.10802012 -0.01018821  0.00854286 -0.07409099
   0.08399387  0.02813234  0.14954358 -0.01133163 -0.02231244 -0.00067821
  -0.01496229 -0.03554197]
 [-0.04522103 -0.04316105 -0.01369646 -0.00553437 -0.02415551  0.08680557
  -0.01702443  0.04189894 -0.05795955  0.05027737  0.03333388 -0.08103316
  -0.01982914 -0.01287705 -0.03231246  0.07074498 -0.00722022  0.06175588
   0.01573111 -0.00602754  0.04581362 -0.05225587 -0.00112576 -0.06373891
   0.00708463  0.02414002 -0.00782012 -0.0117412   0.01960076  0.0168344
  -0.03072136  0.03659785]
 [-0.02771119  0.05902466 -0.0719974  -0.05003864 -0.00503386  0.08406248
   0.00843591 -0.02792032 -0.01560115  0.00499622  0.04903229 -0

## Creating a custom layer with activation function in farward pass

In [20]:
class MyCustomLayer_act(Layer):
    def __init__(self,units=32,**kwargs):
        super(MyCustomLayer_act,self).__init__(**kwargs)
        self.units = units
    def build (self,input_shape):
        print(input_shape[-1])
        self.w = self.add_weight(shape=(input_shape[-1],self.units),initializer='random_normal',trainable=True)
        self.b = self.add_weight(shape=(self.units,),initializer='zeros',trainable=True)
    def call(self,inputs):
        return tf.nn.relu(tf.matmul(inputs,self.w)+self.b)


In [21]:
model=MyCustomLayer_act()

In [22]:
model(input)

11


<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[0.       , 5.6345115, 0.       , 0.       , 0.       , 0.       ,
        0.       , 2.0221603, 0.       , 5.314012 , 0.       , 3.7286084,
        0.       , 0.       , 7.6108365, 3.77652  , 4.0028667, 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        6.734912 , 0.       , 7.6346006, 5.5578194, 0.       , 2.579836 ,
        0.       , 0.       ]], dtype=float32)>

In [24]:
print(input[-1])

tf.Tensor([  1.   2.   3.   2.   1.  12.   1.   1.   2.   1. 121.], shape=(11,), dtype=float32)
